In [3]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Rolling dice

#### Task [5 min]

- Simulate and store the results of rolling a fair, six-sided die 100 times in a one-column table in two ways:
    - Simulating from an array that contains the sides of the die
    - Simulating from a table that contains the sides of the die

In [22]:
die_results = make_array()

In [23]:
die = Table().with_columns('Sides',make_array(1,2,3,4,5,6))
die

Sides
1
2
3
4
5
6

In [24]:
die.sample(1).column('Sides').item(0)

5

In [25]:
for i in np.arange(100):
    new_roll = die.sample(1).column('Sides').item(0)
    die_results = np.append(die_results, new_roll)

In [26]:
die_results

array([ 3.,  6.,  6.,  4.,  6.,  1.,  2.,  5.,  4.,  3.,  1.,  6.,  1.,
        6.,  1.,  1.,  4.,  2.,  5.,  1.,  2.,  5.,  6.,  1.,  6.,  1.,
        4.,  4.,  5.,  1.,  6.,  5.,  5.,  1.,  1.,  1.,  4.,  2.,  3.,
        3.,  4.,  6.,  4.,  1.,  4.,  2.,  1.,  6.,  6.,  2.,  5.,  5.,
        3.,  4.,  1.,  1.,  3.,  6.,  5.,  5.,  1.,  6.,  6.,  6.,  2.,
        5.,  3.,  4.,  6.,  1.,  3.,  6.,  3.,  3.,  1.,  5.,  6.,  4.,
        6.,  3.,  4.,  5.,  5.,  5.,  5.,  1.,  1.,  5.,  6.,  1.,  5.,
        2.,  5.,  6.,  2.,  1.,  3.,  1.,  1.,  2.])

In [12]:
die_table = Table().with_columns('Results', die_results)
die_table

Results
3
3
5
2
2
2
3
5
1
2
... (90 rows omitted)

#### Task [3 min]

- Visualize the distribution of the data in two different ways:
  - Counting the number of rolls per side of the die
  - Counting the number of rolls in each of the following four groups:
    - 1 spot and 2 spots, 3 spots and 4 spots, 5 spots, 6 spots

## Restaurant growth report

#### Task [1 min]

- Read in and store the data in the visualization from the file `restaurant-growth.csv.`

In [29]:
rg = Table.read_table('restaurant-growth.csv')

rg.with_columns('Transaction YOY',
                (rg.column('2024')-rg.column('2023'))/rg.column('2023') * 100)

City         | 2023   | 2024   | Transaction YOY
Atlanta      | 51000  | 51510  | 1
Austin       | 98000  | 98980  | 1
Boston       | 65000  | 64350  | -1
Charlotte    | 92000  | 92000  | 0
Chicago      | 264000 | 271920 | 3
Columbus     | 92000  | 92000  | 0
Dallas       | 130000 | 131300 | 1
Denver       | 72000  | 65520  | -9
Houston      | 232000 | 234320 | 1
Indianapolis | 88000  | 87120  | -1
... (10 rows omitted)

#### Task [5 min]

- Add the 'Transactions YOY' column to the table that you see in the visualization using *two* different methods!
- See if you can use the text to help you (or, just stare at the columns and you'll figure out what to do)!

#### Task [2 min]

- Visualize the distribution of the year-over-year transactions using the plot type in the visualization, but make it easier to see which restaurants saw the most growth.